//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceClientTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebServiceResponse", Namespace="http://deephavenmortgage.com/webservices")]
    [System.SerializableAttribute()]
    public partial class WebServiceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://deephavenmortgage.com/webservices", ConfigurationName="ServiceReference1.SampleWebServiceSoap")]
    public interface SampleWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name firstName from namespace http://deephavenmortgage.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://deephavenmortgage.com/webservices/HelloWorld", ReplyAction="*")]
        WebServiceClientTest.ServiceReference1.HelloWorldResponse HelloWorld(WebServiceClientTest.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://deephavenmortgage.com/webservices/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClientTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync(WebServiceClientTest.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name operation from namespace http://deephavenmortgage.com/webservices is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://deephavenmortgage.com/webservices/Calculator", ReplyAction="*")]
        WebServiceClientTest.ServiceReference1.CalculatorResponse Calculator(WebServiceClientTest.ServiceReference1.CalculatorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://deephavenmortgage.com/webservices/Calculator", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceClientTest.ServiceReference1.CalculatorResponse> CalculatorAsync(WebServiceClientTest.ServiceReference1.CalculatorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://deephavenmortgage.com/webservices", Order=0)]
        public WebServiceClientTest.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceClientTest.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://deephavenmortgage.com/webservices")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string firstName, string lastName) {
            this.firstName = firstName;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://deephavenmortgage.com/webservices", Order=0)]
        public WebServiceClientTest.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceClientTest.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://deephavenmortgage.com/webservices")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Calculator", Namespace="http://deephavenmortgage.com/webservices", Order=0)]
        public WebServiceClientTest.ServiceReference1.CalculatorRequestBody Body;
        
        public CalculatorRequest() {
        }
        
        public CalculatorRequest(WebServiceClientTest.ServiceReference1.CalculatorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://deephavenmortgage.com/webservices")]
    public partial class CalculatorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int firstVal;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int secondVal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string operation;
        
        public CalculatorRequestBody() {
        }
        
        public CalculatorRequestBody(int firstVal, int secondVal, string operation) {
            this.firstVal = firstVal;
            this.secondVal = secondVal;
            this.operation = operation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CalculatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CalculatorResponse", Namespace="http://deephavenmortgage.com/webservices", Order=0)]
        public WebServiceClientTest.ServiceReference1.CalculatorResponseBody Body;
        
        public CalculatorResponse() {
        }
        
        public CalculatorResponse(WebServiceClientTest.ServiceReference1.CalculatorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://deephavenmortgage.com/webservices")]
    public partial class CalculatorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceClientTest.ServiceReference1.WebServiceResponse CalculatorResult;
        
        public CalculatorResponseBody() {
        }
        
        public CalculatorResponseBody(WebServiceClientTest.ServiceReference1.WebServiceResponse CalculatorResult) {
            this.CalculatorResult = CalculatorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SampleWebServiceSoapChannel : WebServiceClientTest.ServiceReference1.SampleWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleWebServiceSoapClient : System.ServiceModel.ClientBase<WebServiceClientTest.ServiceReference1.SampleWebServiceSoap>, WebServiceClientTest.ServiceReference1.SampleWebServiceSoap {
        
        public SampleWebServiceSoapClient() {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClientTest.ServiceReference1.HelloWorldResponse WebServiceClientTest.ServiceReference1.SampleWebServiceSoap.HelloWorld(WebServiceClientTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string firstName, string lastName) {
            WebServiceClientTest.ServiceReference1.HelloWorldRequest inValue = new WebServiceClientTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceClientTest.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            WebServiceClientTest.ServiceReference1.HelloWorldResponse retVal = ((WebServiceClientTest.ServiceReference1.SampleWebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClientTest.ServiceReference1.HelloWorldResponse> WebServiceClientTest.ServiceReference1.SampleWebServiceSoap.HelloWorldAsync(WebServiceClientTest.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClientTest.ServiceReference1.HelloWorldResponse> HelloWorldAsync(string firstName, string lastName) {
            WebServiceClientTest.ServiceReference1.HelloWorldRequest inValue = new WebServiceClientTest.ServiceReference1.HelloWorldRequest();
            inValue.Body = new WebServiceClientTest.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            return ((WebServiceClientTest.ServiceReference1.SampleWebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceClientTest.ServiceReference1.CalculatorResponse WebServiceClientTest.ServiceReference1.SampleWebServiceSoap.Calculator(WebServiceClientTest.ServiceReference1.CalculatorRequest request) {
            return base.Channel.Calculator(request);
        }
        
        public WebServiceClientTest.ServiceReference1.WebServiceResponse Calculator(int firstVal, int secondVal, string operation) {
            WebServiceClientTest.ServiceReference1.CalculatorRequest inValue = new WebServiceClientTest.ServiceReference1.CalculatorRequest();
            inValue.Body = new WebServiceClientTest.ServiceReference1.CalculatorRequestBody();
            inValue.Body.firstVal = firstVal;
            inValue.Body.secondVal = secondVal;
            inValue.Body.operation = operation;
            WebServiceClientTest.ServiceReference1.CalculatorResponse retVal = ((WebServiceClientTest.ServiceReference1.SampleWebServiceSoap)(this)).Calculator(inValue);
            return retVal.Body.CalculatorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceClientTest.ServiceReference1.CalculatorResponse> WebServiceClientTest.ServiceReference1.SampleWebServiceSoap.CalculatorAsync(WebServiceClientTest.ServiceReference1.CalculatorRequest request) {
            return base.Channel.CalculatorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceClientTest.ServiceReference1.CalculatorResponse> CalculatorAsync(int firstVal, int secondVal, string operation) {
            WebServiceClientTest.ServiceReference1.CalculatorRequest inValue = new WebServiceClientTest.ServiceReference1.CalculatorRequest();
            inValue.Body = new WebServiceClientTest.ServiceReference1.CalculatorRequestBody();
            inValue.Body.firstVal = firstVal;
            inValue.Body.secondVal = secondVal;
            inValue.Body.operation = operation;
            return ((WebServiceClientTest.ServiceReference1.SampleWebServiceSoap)(this)).CalculatorAsync(inValue);
        }
    }
}
